CREATE TABLE IF NOT EXISTS mods (
    id VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    author VARCHAR(120) NOT NULL,
    version VARCHAR(32) NOT NULL,
    category VARCHAR(64) NOT NULL DEFAULT 'Mod',
    icon VARCHAR(16) NOT NULL DEFAULT 'MOD',
    min_app_version VARCHAR(32) NOT NULL DEFAULT '0.4.0',
    package_format VARCHAR(16) NOT NULL DEFAULT 'rcc-v1',
    entry_path VARCHAR(255) NOT NULL DEFAULT 'Main.qml',
    object_key VARCHAR(512) NOT NULL,
    sha256 CHAR(64) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    downloads BIGINT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('draft', 'published', 'disabled') NOT NULL DEFAULT 'published',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    published_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_mods_status_updated (status, updated_at),
    KEY idx_mods_category (category),
    KEY idx_mods_downloads (downloads)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
