// SPDX-License-Identifier: LicenseRef-LMG-SAPEL-1.0
#include "DeveloperManager.h"
#include "AppPaths.h"
#include "GameRegistry.h"
#include "GameRuntime.h"
#include "PluginDiagnostics.h"
#include <QCryptographicHash>
#include <QDesktopServices>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QRegularExpression>
#include <QtGlobal>
namespace { constexpr qint64 kMaxRccBytes=64LL*1024LL*1024LL; constexpr qint64 kMaxAuthResponse=512LL*1024LL; const QUrl kPortal(QStringLiteral("https://leominigames.younglion.xyz/developer/")); const QUrl kVerify(QStringLiteral("https://leominigames.younglion.xyz/api/v1/developer/contents")); }
DeveloperManager::DeveloperManager(AppPaths*p,GameRegistry*g,PluginDiagnostics*d,QObject*parent):QObject(parent),m_paths(p),m_games(g),m_diagnostics(d),m_network(new QNetworkAccessManager(this)){setStatus(QStringLiteral("Developer Mode is locked."));}
DeveloperManager::~DeveloperManager(){clearImported();}
QVariantList DeveloperManager::deviceProfiles() const{return {QVariantMap{{"name","Current window"},{"width",0},{"height",0},{"safeTop",0},{"safeBottom",0}},QVariantMap{{"name","Small Android Phone"},{"width",360},{"height",640},{"safeTop",24},{"safeBottom",24}},QVariantMap{{"name","Large Android Phone"},{"width",412},{"height",915},{"safeTop",32},{"safeBottom",24}},QVariantMap{{"name","Tablet"},{"width",800},{"height",1280},{"safeTop",24},{"safeBottom",24}},QVariantMap{{"name","Desktop 1366x768"},{"width",1366},{"height",768},{"safeTop",0},{"safeBottom",0}},QVariantMap{{"name","Desktop 1920x1080"},{"width",1920},{"height",1080},{"safeTop",0},{"safeBottom",0}},QVariantMap{{"name","Ultrawide"},{"width",2560},{"height",1080},{"safeTop",0},{"safeBottom",0}},QVariantMap{{"name","Landscape mobile"},{"width",915},{"height",412},{"safeTop",0},{"safeBottom",16}}};}

QString DeveloperManager::profileName() const { const QVariantList p=deviceProfiles(); return m_selectedProfile>=0&&m_selectedProfile<p.size()?p.at(m_selectedProfile).toMap().value(QStringLiteral("name")).toString():QStringLiteral("Current window"); }
qreal DeveloperManager::profileWidth() const { const QVariantList p=deviceProfiles(); return m_selectedProfile>=0&&m_selectedProfile<p.size()?p.at(m_selectedProfile).toMap().value(QStringLiteral("width")).toReal():0.0; }
qreal DeveloperManager::profileHeight() const { const QVariantList p=deviceProfiles(); return m_selectedProfile>=0&&m_selectedProfile<p.size()?p.at(m_selectedProfile).toMap().value(QStringLiteral("height")).toReal():0.0; }
qreal DeveloperManager::profileSafeTop() const { const QVariantList p=deviceProfiles(); return m_selectedProfile>=0&&m_selectedProfile<p.size()?p.at(m_selectedProfile).toMap().value(QStringLiteral("safeTop")).toReal():0.0; }
qreal DeveloperManager::profileSafeBottom() const { const QVariantList p=deviceProfiles(); return m_selectedProfile>=0&&m_selectedProfile<p.size()?p.at(m_selectedProfile).toMap().value(QStringLiteral("safeBottom")).toReal():0.0; }
void DeveloperManager::selectDeviceProfile(int index){const int max=deviceProfiles().size()-1;const int v=qBound(0,index,max);if(m_selectedProfile==v)return;m_selectedProfile=v;emit profileChanged();}
void DeveloperManager::setError(const QString&m){m_error=m;if(!m.isEmpty()&&m_diagnostics)m_diagnostics->log(QStringLiteral("error"),m,QStringLiteral("DeveloperManager"),0);emit changed();} void DeveloperManager::setStatus(const QString&m){m_status=m;emit changed();}
void DeveloperManager::openDeveloperPortal(){QDesktopServices::openUrl(kPortal);}
bool DeveloperManager::safeKeyFormat(const QString&key){static const QRegularExpression re(QStringLiteral("^lmg_[0-9a-f]{12}_[A-Za-z0-9_-]{40,60}$"));return re.match(key).hasMatch();}
void DeveloperManager::verifyApiKey(const QString &apiKey)
{
    if(m_verifying)return; const QString key=apiKey.trimmed(); if(!safeKeyFormat(key)){setError(QStringLiteral("Invalid developer API-key format."));return;} m_verifying=true;m_error.clear();setStatus(QStringLiteral("Verifying developer account…"));emit changed();
    QNetworkRequest req(kVerify);req.setRawHeader("Accept","application/json");req.setRawHeader("Authorization",QByteArrayLiteral("Bearer ")+key.toUtf8());req.setHeader(QNetworkRequest::UserAgentHeader,QStringLiteral("LeoMiniGames/0.7.0 DeveloperLab"));req.setTransferTimeout(15000);req.setAttribute(QNetworkRequest::RedirectPolicyAttribute,QNetworkRequest::ManualRedirectPolicy);
    QNetworkReply *reply=m_network->get(req);connect(reply,&QNetworkReply::finished,this,[this,reply]{const QByteArray payload=reply->read(kMaxAuthResponse+1);const int http=reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();const bool redirected=reply->attribute(QNetworkRequest::RedirectionTargetAttribute).isValid();const auto networkError=reply->error();reply->deleteLater();m_verifying=false;if(redirected){m_authenticated=false;setStatus(QStringLiteral("Developer Mode is locked."));setError(QStringLiteral("Developer authentication refused an HTTP redirect."));return;}if(payload.size()>kMaxAuthResponse){m_authenticated=false;setStatus(QStringLiteral("Developer Mode is locked."));setError(QStringLiteral("Developer authentication response exceeded the safety limit."));return;}QJsonParseError e{};const QJsonDocument doc=QJsonDocument::fromJson(payload,&e);if(networkError!=QNetworkReply::NoError||http<200||http>=300||e.error!=QJsonParseError::NoError||!doc.isObject()){m_authenticated=false;setStatus(QStringLiteral("Developer Mode is locked."));setError(QStringLiteral("Developer credential verification failed."));return;}const QJsonObject root=doc.object();const QJsonObject data=root.value(QStringLiteral("data")).toObject();if(data.isEmpty()||!data.value(QStringLiteral("items")).isArray()){m_authenticated=false;setStatus(QStringLiteral("Developer Mode is locked."));setError(QStringLiteral("Developer credential response did not match the expected API contract."));return;}m_authenticated=true;m_error.clear();setStatus(QStringLiteral("Developer Mode active for this session. API key was not persisted."));emit changed();});
}
QString DeveloperManager::sha256File(const QString&p){QFile f(p);if(!f.open(QIODevice::ReadOnly))return QString();QCryptographicHash h(QCryptographicHash::Sha256);while(!f.atEnd())h.addData(f.read(1024*1024));return QString::fromLatin1(h.result().toHex());}
bool DeveloperManager::importRcc(const QUrl &sourceFile)
{
    if(!m_authenticated){setError(QStringLiteral("Authenticate a developer account before importing local RCC packages."));return false;}if(!sourceFile.isLocalFile()){setError(QStringLiteral("Developer Lab accepts local RCC files only."));return false;}const QString source=sourceFile.toLocalFile();const QFileInfo info(source);if(!info.isFile()||info.size()<=0||info.size()>kMaxRccBytes){setError(QStringLiteral("RCC file is missing, empty, or exceeds 64 MiB."));return false;}
    clearImported();const QString digest=sha256File(source);if(digest.size()!=64){setError(QStringLiteral("Could not hash local RCC package."));return false;}const QString dir=m_paths->cache()+QStringLiteral("/developer-lab");QDir().mkpath(dir);const QString copy=dir+QLatin1Char('/')+digest+QStringLiteral(".rcc");if(QFileInfo::exists(copy))QFile::remove(copy);if(!QFile::copy(source,copy)||sha256File(copy)!=digest){QFile::remove(copy);setError(QStringLiteral("Could not create a verified session copy of the RCC package."));return false;}
    RccPackageInspection inspection=RccPackageInspector::inspect(copy);if(!inspection.valid){QFile::remove(copy);setError(QStringLiteral("RCC validation failed: %1").arg(inspection.error));return false;}
    {
        const QJsonObject manifest=inspection.manifest;
        QStringList required;
        for(const QJsonValue &value:manifest.value(QStringLiteral("required_capabilities")).toArray()) required.append(value.toString());
        GameRuntime runtime;
        const QVariantMap compatibility=runtime.checkCompatibility(manifest.value(QStringLiteral("api_version")).toString(),manifest.value(QStringLiteral("min_api_version")).toString(),required);
        if(!compatibility.value(QStringLiteral("ok")).toBool()){QFile::remove(copy);setError(QStringLiteral("RCC API compatibility failed: %1").arg(compatibility.value(QStringLiteral("error")).toString()));return false;}
    }
    if(m_games&&!m_games->versionFor(inspection.packageId).isEmpty()){QFile::remove(copy);setError(QStringLiteral("Local package id collides with an installed or built-in game."));return false;}if(!RccPackageInspector::mount(copy,inspection)){QFile::remove(copy);setError(QStringLiteral("Validated RCC could not be mounted."));return false;}
    m_rccFile=copy;m_inspection=inspection;const QJsonObject m=inspection.manifest;QStringList locales;for(const QJsonValue&v:m.value(QStringLiteral("locales")).toArray())locales<<v.toString();QStringList capabilities;for(const QJsonValue&v:m.value(QStringLiteral("capabilities")).toArray())capabilities<<v.toString();m_packageInfo={{QStringLiteral("id"),inspection.packageId},{QStringLiteral("version"),m.value(QStringLiteral("version")).toString(QStringLiteral("dev"))},{QStringLiteral("packageFormat"),m.value(QStringLiteral("package_format")).toString(QStringLiteral("rcc-v1"))},{QStringLiteral("entry"),inspection.entryPath},{QStringLiteral("apiVersion"),m.value(QStringLiteral("api_version")).toString(QStringLiteral("legacy"))},{QStringLiteral("minApiVersion"),m.value(QStringLiteral("min_api_version")).toString()},{QStringLiteral("capabilities"),capabilities},{QStringLiteral("publisher"),m.value(QStringLiteral("publisher")).toString(m.value(QStringLiteral("author")).toString(QStringLiteral("Local developer")))},{QStringLiteral("publisherTrust"),QStringLiteral("local-unverified")},{QStringLiteral("mountMode"),inspection.legacyLayout?QStringLiteral("legacy"):QStringLiteral("canonical")},{QStringLiteral("resourceCount"),inspection.resources.size()},{QStringLiteral("locales"),locales},{QStringLiteral("defaultLocale"),m.value(QStringLiteral("default_locale")).toString(QStringLiteral("en"))},{QStringLiteral("saveVersion"),qMax(1,m.value(QStringLiteral("save_version")).toInt(1))},{QStringLiteral("nativeRequested"),m.value(QStringLiteral("native")).toBool(false)||m.value(QStringLiteral("plugin_level")).toInt(1)>=3},{QStringLiteral("nativeGranted"),false},{QStringLiteral("sha256"),digest}};m_error.clear();setStatus(QStringLiteral("Local RCC validated and mounted for this session."));emit packageChanged();return true;
}
bool DeveloperManager::launchImported(){if(m_rccFile.isEmpty()||!m_inspection.valid){setError(QStringLiteral("Import a valid RCC first."));return false;}emit launchRequested(m_inspection.packageId,QUrl(QStringLiteral("qrc:/mods/%1/%2").arg(m_inspection.packageId,m_inspection.entryPath)),m_packageInfo.value(QStringLiteral("version")).toString());return true;}
void DeveloperManager::clearImported(){if(!m_rccFile.isEmpty()&&m_inspection.valid)RccPackageInspector::unmount(m_rccFile,m_inspection);if(!m_rccFile.isEmpty())QFile::remove(m_rccFile);m_rccFile.clear();m_inspection=RccPackageInspection{};m_packageInfo.clear();emit packageChanged();}
void DeveloperManager::logout(){clearImported();m_authenticated=false;m_verifying=false;m_error.clear();setStatus(QStringLiteral("Developer Mode is locked."));emit changed();}
QVariantMap DeveloperManager::settingsSchemaFor(const QString&id)const{return id==m_inspection.packageId?m_inspection.manifest.value(QStringLiteral("settings_schema")).toObject().toVariantMap():QVariantMap{};} QStringList DeveloperManager::localesFor(const QString&id)const{QStringList r;if(id==m_inspection.packageId)for(const QJsonValue&v:m_inspection.manifest.value(QStringLiteral("locales")).toArray())r<<v.toString();return r;} QString DeveloperManager::defaultLocaleFor(const QString&id)const{return id==m_inspection.packageId?m_inspection.manifest.value(QStringLiteral("default_locale")).toString(QStringLiteral("en")):QStringLiteral("en");} int DeveloperManager::saveVersionFor(const QString&id)const{return id==m_inspection.packageId?qMax(1,m_inspection.manifest.value(QStringLiteral("save_version")).toInt(1)):1;}
